name: Deploy Vite React App
 
on:
  push:
    branches: [production]  # Trigger on pushes to the main branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      VITE_API_BASE_URL: "https://api.zapcart.zapelite.com"
 
 
    steps:
      - uses: actions/checkout@v3
 
      - name: Install dependencies
        run: npm install
        
      - name: Build React app
        run: npm run build
 
      - name: Deploy to VPS using SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          source: "dist/*"  # Or "out" if using `next export`
          target: "/var/www/admin.zapcart.zapelite.com/"
          
      - name: Run command on remote
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
          script: |
            sudo systemctl restart nginx
